In [3]:
import csv
import pandas as pd

# Replace 'data.tsv' with the path to your TSV file
tsv_file = 'Sample.tsv'

# Initialize an empty list to store the data from the TSV file
data = []

# Read the TSV file and store its content in the 'data' list
with open(tsv_file, 'r', newline='', encoding='utf-8') as file:
    reader = csv.reader(file, delimiter='\t')
    for row in reader:
        data.append(row)

df = pd.DataFrame(data[1:], columns=data[0])

In [4]:
df

,user_id,score,date,review,is_month,is_repurch
0,sati*****,5,23.08.01.,진짜 귀얍게 잘 갖고 놀아요,True,False
1,kb****,5,23.07.03.,강아지 최애 공입니다. 노랑색을 유난히 좋아하네요,True,False
2,kare*****,5,23.05.24.,노견 푸들이 공놀이를 너무 좋아하는데 이빨이 약해서 탄탄한 공은 잘 못 물더라구요....,False,False
3,cm****,5,23.05.18.,저희 강아지가 진짜 좋아하는 공이라 여러개 샀는데 좋아요,True,False
4,meji****,5,22.11.10.,온것중에 빨강이 골라서 줬는데 환장하구 놀아욤 !!\n막 뜯어버리는 애도 아니고 짱...,False,False
...,...,...,...,...,...,...
63,haha****,5,17.10.28.,잘삿어요 이건 뜯지도 못하고 애들이 잘가지고 노네요 ㅎㅎ\n잘산거같아요ㅎㅎ 견당 하...,False,False
64,haha****,5,17.10.28.,만족합니다,False,False
65,hyun*****,5,17.10.12.,너무너무 좋아하네요 5분만에 삑삑이 고장내고도 계속 가지고 놀아요 ^^,False,False
66,ooy_***,5,17.10.20.,배송도 빠르고 강아지가 좋아해요^^,False,False
67,pine*****,5,17.10.15.,배송도 빠르고 좋아요,False,False